package com.prem.share.dm.db.dao;

import com.prem.share.dm.db.Commodity;
import com.prem.share.dm.db.CommodityExample;
import java.util.List;

public interface CommodityDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int countCommodityByExample(CommodityExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int deleteCommodityByExample(CommodityExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int deleteCommodityByPrimaryKey(String commodityId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    void insertCommodity(Commodity record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    void insertCommoditySelective(Commodity record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    List<Commodity> selectCommodityByExample(CommodityExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    Commodity selectCommodityByPrimaryKey(String commodityId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int updateCommodityByExampleSelective(Commodity record, CommodityExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int updateCommodityByExample(Commodity record, CommodityExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int updateCommodityByPrimaryKeySelective(Commodity record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int updateCommodityByPrimaryKey(Commodity record);
}