/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IPV6.java
 *
 * Created on May 7, 2010, 10:28:57 PM
 */

package com.prem.share.gui;

import java.io.IOException;
import java.io.Reader;
import java.util.List;

import org.springframework.beans.factory.BeanFactory;
import org.springframework.beans.factory.xml.XmlBeanFactory;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;

import com.ibatis.common.resources.Resources;
import com.ibatis.sqlmap.client.SqlMapClient;
import com.ibatis.sqlmap.client.SqlMapClientBuilder;
import com.prem.share.dm.db.brokerage;
import com.prem.share.dm.db.share_broker;
import com.prem.share.dm.db.share_brokerExample;
import com.prem.share.dm.db.dao.impl.share_brokerDAOImpl;
import com.prem.share.dm.db.share_brokerExample.Criteria;


/**
 *
 * @author Administrator
 */
public class TradePanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form IPV6 */
    public TradePanel() {
        init();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void init() {
        brokeragePanel = new javax.swing.JPanel();
        tradeTypeLabel = new javax.swing.JLabel();
        brokerageLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        sttLabel = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        serviceTaxLabel = new javax.swing.JLabel();
        dayTradeLabel = new javax.swing.JLabel();
        deliveryTradeLabel = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        brokeragePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        brokeragePanel.setName("brokeragePanel"); // NOI18N

        tradeTypeLabel.setText("Trade Type");
        tradeTypeLabel.setName("tradeTypeLabel"); // NOI18N

        brokerageLabel.setText("Brokerage");
        brokerageLabel.setName("brokerageLabel"); // NOI18N

        sttLabel.setText("STT");
        sttLabel.setName("sttLabel"); // NOI18N

        serviceTaxLabel.setText("Service Tax");
        serviceTaxLabel.setName("serviceTaxLabel"); // NOI18N

        dayTradeLabel.setText("Day Trade");
        dayTradeLabel.setName("dayTradeLabel"); // NOI18N

        deliveryTradeLabel.setText("Delivery Trade");
        deliveryTradeLabel.setName("deliveryTradeLabel"); // NOI18N

        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField1.setName("jTextField1"); // NOI18N

        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField2.setName("jTextField2"); // NOI18N

        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField3.setName("jTextField3"); // NOI18N


        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField4.setName("jTextField4"); // NOI18N

        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField5.setName("jTextField5"); // NOI18N

        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField6.setName("jTextField6"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(brokeragePanel);
        brokeragePanel.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tradeTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brokerageLabel)
                    .addComponent(sttLabel)
                    .addComponent(serviceTaxLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayTradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deliveryTradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(294, 294, 294))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tradeTypeLabel)
                    .addComponent(dayTradeLabel)
                    .addComponent(deliveryTradeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brokerageLabel)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sttLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serviceTaxLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brokeragePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(brokeragePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JLabel tradeTypeLabel;
    private javax.swing.JLabel brokerageLabel;
    private javax.swing.JLabel sttLabel;
    private javax.swing.JLabel serviceTaxLabel;
    private javax.swing.JLabel dayTradeLabel;
    private javax.swing.JLabel deliveryTradeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel brokeragePanel;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration

    public static void main(String argv[]) {
//    	Reader rd = null;
//		try {
//			rd = Resources.getResourceAsReader("SqlMapConfig.xml");
//		} catch (IOException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//    	   SqlMapClient smc = SqlMapClientBuilder.buildSqlMapClient(rd);
//    	   smc.q
    	share_brokerExample sb = new share_brokerExample();
    	sb.createCriteria().andNameEqualTo("Sharekhan");
    	
    	Resource resource = new FileSystemResource(
    		"src/com/prem/share/dm/db/maps/spring-ibatis.xml");
    	BeanFactory beanFactory = new XmlBeanFactory(resource);
    	share_brokerDAOImpl share_brokerImpl = (share_brokerDAOImpl)beanFactory.getBean("share_broker");
    	List<share_broker> ls = share_brokerImpl.selectshare_brokerByExample(sb);

//    	share_brokerDAOImpl sbImpl = new share_brokerDAOImpl();
//    	sbImpl.getSqlMapClient();
//    	System.out.println(sbImpl.selectshare_brokerByExample(sb));
//    	System.out.println(sbImpl.countshare_brokerByExample(sb));
//    	share_broker sb1 = share_brokerDAOImpl.countshare_brokerByExample(sb);
//    	List ls = ct.getCriteriaWithListValue();
//    	List ls = sb.createCriteria().andNameIsNotNull().getCriteriaWithListValue();
    	
    	for(int i =0 ; i<ls.size(); i++) {
    		
    		System.out.println("Name: " + ls.get(i).getId());
    		System.out.println("Name: " + ls.get(i).getName());
    		System.out.println("Name: " + ls.get(i).getDescription());
    	}
//    	brokerage br = new brokerage();
//    	br.set
    }
}
