package com.prem.share.dm.db;

import java.io.Serializable;

public class ShareBroker implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column share_broker.id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column share_broker.name
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column share_broker.description
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private String description;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table share_broker
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column share_broker.id
	 * @return  the value of share_broker.id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column share_broker.id
	 * @param id  the value for share_broker.id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column share_broker.name
	 * @return  the value of share_broker.name
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column share_broker.name
	 * @param name  the value for share_broker.name
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column share_broker.description
	 * @return  the value of share_broker.description
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column share_broker.description
	 * @param description  the value for share_broker.description
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}