package com.prem.share.dm.db;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class EquityTransaction implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.transaction_id
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	private Integer transactionId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.SCRIPT_script_ID
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	private String scriptScriptId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.transaction_type
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	private String transactionType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.transaction_date
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	private Date transactionDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.quantity
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	private Integer quantity;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.price
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	private BigDecimal price;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.market_value
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	private BigDecimal marketValue;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.extra_charges
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	private BigDecimal extraCharges;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.actual_value
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	private BigDecimal actualValue;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.script_status
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	private String scriptStatus;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.contract_no
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	private Integer contractNo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.client_code
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	private String clientCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table equity_transaction
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.transaction_id
	 * @return  the value of equity_transaction.transaction_id
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public Integer getTransactionId() {
		return transactionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.transaction_id
	 * @param transactionId  the value for equity_transaction.transaction_id
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.SCRIPT_script_ID
	 * @return  the value of equity_transaction.SCRIPT_script_ID
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public String getScriptScriptId() {
		return scriptScriptId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.SCRIPT_script_ID
	 * @param scriptScriptId  the value for equity_transaction.SCRIPT_script_ID
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public void setScriptScriptId(String scriptScriptId) {
		this.scriptScriptId = scriptScriptId == null ? null : scriptScriptId
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.transaction_type
	 * @return  the value of equity_transaction.transaction_type
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public String getTransactionType() {
		return transactionType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.transaction_type
	 * @param transactionType  the value for equity_transaction.transaction_type
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType == null ? null : transactionType
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.transaction_date
	 * @return  the value of equity_transaction.transaction_date
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public Date getTransactionDate() {
		return transactionDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.transaction_date
	 * @param transactionDate  the value for equity_transaction.transaction_date
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.quantity
	 * @return  the value of equity_transaction.quantity
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.quantity
	 * @param quantity  the value for equity_transaction.quantity
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.price
	 * @return  the value of equity_transaction.price
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.price
	 * @param price  the value for equity_transaction.price
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.market_value
	 * @return  the value of equity_transaction.market_value
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public BigDecimal getMarketValue() {
		return marketValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.market_value
	 * @param marketValue  the value for equity_transaction.market_value
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public void setMarketValue(BigDecimal marketValue) {
		this.marketValue = marketValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.extra_charges
	 * @return  the value of equity_transaction.extra_charges
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public BigDecimal getExtraCharges() {
		return extraCharges;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.extra_charges
	 * @param extraCharges  the value for equity_transaction.extra_charges
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public void setExtraCharges(BigDecimal extraCharges) {
		this.extraCharges = extraCharges;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.actual_value
	 * @return  the value of equity_transaction.actual_value
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public BigDecimal getActualValue() {
		return actualValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.actual_value
	 * @param actualValue  the value for equity_transaction.actual_value
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public void setActualValue(BigDecimal actualValue) {
		this.actualValue = actualValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.script_status
	 * @return  the value of equity_transaction.script_status
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public String getScriptStatus() {
		return scriptStatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.script_status
	 * @param scriptStatus  the value for equity_transaction.script_status
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public void setScriptStatus(String scriptStatus) {
		this.scriptStatus = scriptStatus == null ? null : scriptStatus.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.contract_no
	 * @return  the value of equity_transaction.contract_no
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public Integer getContractNo() {
		return contractNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.contract_no
	 * @param contractNo  the value for equity_transaction.contract_no
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public void setContractNo(Integer contractNo) {
		this.contractNo = contractNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.client_code
	 * @return  the value of equity_transaction.client_code
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public String getClientCode() {
		return clientCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.client_code
	 * @param clientCode  the value for equity_transaction.client_code
	 * @ibatorgenerated  Mon Oct 24 16:28:18 IST 2011
	 */
	public void setClientCode(String clientCode) {
		this.clientCode = clientCode == null ? null : clientCode.trim();
	}
}