package com.prem.share.dm.db;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class EquityTransaction implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.transaction_id
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	private Integer transactionId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.SCRIPT_script_ID
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	private String scriptScriptId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.transaction_type
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	private String transactionType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.transaction_date
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	private Date transactionDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.quantity
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	private Integer quantity;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.price
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	private BigDecimal price;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.market_buy_value
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	private BigDecimal marketBuyValue;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.extra_charges
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	private BigDecimal extraCharges;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.actual_buy_value
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	private BigDecimal actualBuyValue;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column equity_transaction.script_status
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	private String scriptStatus;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table equity_transaction
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.transaction_id
	 * @return  the value of equity_transaction.transaction_id
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public Integer getTransactionId() {
		return transactionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.transaction_id
	 * @param transactionId  the value for equity_transaction.transaction_id
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.SCRIPT_script_ID
	 * @return  the value of equity_transaction.SCRIPT_script_ID
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public String getScriptScriptId() {
		return scriptScriptId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.SCRIPT_script_ID
	 * @param scriptScriptId  the value for equity_transaction.SCRIPT_script_ID
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public void setScriptScriptId(String scriptScriptId) {
		this.scriptScriptId = scriptScriptId == null ? null : scriptScriptId
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.transaction_type
	 * @return  the value of equity_transaction.transaction_type
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public String getTransactionType() {
		return transactionType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.transaction_type
	 * @param transactionType  the value for equity_transaction.transaction_type
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType == null ? null : transactionType
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.transaction_date
	 * @return  the value of equity_transaction.transaction_date
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public Date getTransactionDate() {
		return transactionDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.transaction_date
	 * @param transactionDate  the value for equity_transaction.transaction_date
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.quantity
	 * @return  the value of equity_transaction.quantity
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.quantity
	 * @param quantity  the value for equity_transaction.quantity
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.price
	 * @return  the value of equity_transaction.price
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.price
	 * @param price  the value for equity_transaction.price
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.market_buy_value
	 * @return  the value of equity_transaction.market_buy_value
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public BigDecimal getMarketBuyValue() {
		return marketBuyValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.market_buy_value
	 * @param marketBuyValue  the value for equity_transaction.market_buy_value
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public void setMarketBuyValue(BigDecimal marketBuyValue) {
		this.marketBuyValue = marketBuyValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.extra_charges
	 * @return  the value of equity_transaction.extra_charges
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public BigDecimal getExtraCharges() {
		return extraCharges;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.extra_charges
	 * @param extraCharges  the value for equity_transaction.extra_charges
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public void setExtraCharges(BigDecimal extraCharges) {
		this.extraCharges = extraCharges;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.actual_buy_value
	 * @return  the value of equity_transaction.actual_buy_value
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public BigDecimal getActualBuyValue() {
		return actualBuyValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.actual_buy_value
	 * @param actualBuyValue  the value for equity_transaction.actual_buy_value
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public void setActualBuyValue(BigDecimal actualBuyValue) {
		this.actualBuyValue = actualBuyValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column equity_transaction.script_status
	 * @return  the value of equity_transaction.script_status
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public String getScriptStatus() {
		return scriptStatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column equity_transaction.script_status
	 * @param scriptStatus  the value for equity_transaction.script_status
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	public void setScriptStatus(String scriptStatus) {
		this.scriptStatus = scriptStatus == null ? null : scriptStatus.trim();
	}
}