package com.prem.share.dm.db;

import java.io.Serializable;
import java.math.BigDecimal;

public class Script implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column script.script_id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private String scriptId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column script.script_name
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private String scriptName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column script.description
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private String description;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column script.url
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private String url;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column script.face_value
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private BigDecimal faceValue;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column script.sharekhan_id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private String sharekhanId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column script.rediff_id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private String rediffId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column script.yahoo_id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private String yahooId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column script.favorite
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private Integer favorite;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table script
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column script.script_id
	 * @return  the value of script.script_id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public String getScriptId() {
		return scriptId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column script.script_id
	 * @param scriptId  the value for script.script_id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public void setScriptId(String scriptId) {
		this.scriptId = scriptId == null ? null : scriptId.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column script.script_name
	 * @return  the value of script.script_name
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public String getScriptName() {
		return scriptName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column script.script_name
	 * @param scriptName  the value for script.script_name
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public void setScriptName(String scriptName) {
		this.scriptName = scriptName == null ? null : scriptName.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column script.description
	 * @return  the value of script.description
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column script.description
	 * @param description  the value for script.description
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column script.url
	 * @return  the value of script.url
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column script.url
	 * @param url  the value for script.url
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column script.face_value
	 * @return  the value of script.face_value
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public BigDecimal getFaceValue() {
		return faceValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column script.face_value
	 * @param faceValue  the value for script.face_value
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public void setFaceValue(BigDecimal faceValue) {
		this.faceValue = faceValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column script.sharekhan_id
	 * @return  the value of script.sharekhan_id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public String getSharekhanId() {
		return sharekhanId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column script.sharekhan_id
	 * @param sharekhanId  the value for script.sharekhan_id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public void setSharekhanId(String sharekhanId) {
		this.sharekhanId = sharekhanId == null ? null : sharekhanId.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column script.rediff_id
	 * @return  the value of script.rediff_id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public String getRediffId() {
		return rediffId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column script.rediff_id
	 * @param rediffId  the value for script.rediff_id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public void setRediffId(String rediffId) {
		this.rediffId = rediffId == null ? null : rediffId.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column script.yahoo_id
	 * @return  the value of script.yahoo_id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public String getYahooId() {
		return yahooId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column script.yahoo_id
	 * @param yahooId  the value for script.yahoo_id
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public void setYahooId(String yahooId) {
		this.yahooId = yahooId == null ? null : yahooId.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column script.favorite
	 * @return  the value of script.favorite
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public Integer getFavorite() {
		return favorite;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column script.favorite
	 * @param favorite  the value for script.favorite
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	public void setFavorite(Integer favorite) {
		this.favorite = favorite;
	}
}