package com.prem.share.dm.db.dao;

import com.prem.share.dm.db.share_broker;
import com.prem.share.dm.db.share_brokerExample;
import java.util.List;

public interface share_brokerDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    int countshare_brokerByExample(share_brokerExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    int deleteshare_brokerByExample(share_brokerExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    int deleteshare_brokerByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    void insertshare_broker(share_broker record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    void insertshare_brokerSelective(share_broker record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    List<share_broker> selectshare_brokerByExample(share_brokerExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    share_broker selectshare_brokerByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    int updateshare_brokerByExampleSelective(share_broker record, share_brokerExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    int updateshare_brokerByExample(share_broker record, share_brokerExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    int updateshare_brokerByPrimaryKeySelective(share_broker record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    int updateshare_brokerByPrimaryKey(share_broker record);
}