package com.prem.share.dm.db.dao;

import java.util.List;

import com.prem.share.dm.db.Brokerage;
import com.prem.share.dm.db.BrokerageExample;

public interface BrokerageDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table brokerage
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	int countBrokerageByExample(BrokerageExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table brokerage
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	int deleteBrokerageByExample(BrokerageExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table brokerage
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	void insertBrokerage(Brokerage record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table brokerage
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	void insertBrokerageSelective(Brokerage record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table brokerage
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	List<Brokerage> selectBrokerageByExample(BrokerageExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table brokerage
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	int updateBrokerageByExampleSelective(Brokerage record,
			BrokerageExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table brokerage
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	int updateBrokerageByExample(Brokerage record, BrokerageExample example);
}