package com.prem.share.dm.db.dao;

import com.prem.share.dm.db.CommodityTransaction;
import com.prem.share.dm.db.CommodityTransactionExample;
import java.util.List;

public interface CommodityTransactionDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int countCommodityTransactionByExample(CommodityTransactionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int deleteCommodityTransactionByExample(CommodityTransactionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int deleteCommodityTransactionByPrimaryKey(Integer transactionId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    void insertCommodityTransaction(CommodityTransaction record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    void insertCommodityTransactionSelective(CommodityTransaction record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    List<CommodityTransaction> selectCommodityTransactionByExample(CommodityTransactionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    CommodityTransaction selectCommodityTransactionByPrimaryKey(Integer transactionId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int updateCommodityTransactionByExampleSelective(CommodityTransaction record, CommodityTransactionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int updateCommodityTransactionByExample(CommodityTransaction record, CommodityTransactionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int updateCommodityTransactionByPrimaryKeySelective(CommodityTransaction record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int updateCommodityTransactionByPrimaryKey(CommodityTransaction record);
}