package com.prem.share.dm.db.dao;

import java.util.List;

import com.prem.share.dm.db.Script;
import com.prem.share.dm.db.ScriptExample;

public interface ScriptDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	int countScriptByExample(ScriptExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	int deleteScriptByExample(ScriptExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	int deleteScriptByPrimaryKey(String scriptId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	void insertScript(Script record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	void insertScriptSelective(Script record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	List<Script> selectScriptByExample(ScriptExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	Script selectScriptByPrimaryKey(String scriptId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	int updateScriptByExampleSelective(Script record, ScriptExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	int updateScriptByExample(Script record, ScriptExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	int updateScriptByPrimaryKeySelective(Script record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Thu Aug 18 12:42:12 IST 2011
	 */
	int updateScriptByPrimaryKey(Script record);
}