package com.prem.share.dm.db.dao;

import com.prem.share.dm.db.Script;
import com.prem.share.dm.db.ScriptExample;
import java.util.List;

public interface ScriptDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	int countScriptByExample(ScriptExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	int deleteScriptByExample(ScriptExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	int deleteScriptByPrimaryKey(String scriptId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	void insertScript(Script record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	void insertScriptSelective(Script record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	List<Script> selectScriptByExample(ScriptExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	Script selectScriptByPrimaryKey(String scriptId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	int updateScriptByExampleSelective(Script record, ScriptExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	int updateScriptByExample(Script record, ScriptExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	int updateScriptByPrimaryKeySelective(Script record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table script
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	int updateScriptByPrimaryKey(Script record);
}