package com.prem.share.dm.db.dao;

import com.prem.share.dm.db.ShareBroker;
import com.prem.share.dm.db.ShareBrokerExample;
import java.util.List;

public interface ShareBrokerDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int countShareBrokerByExample(ShareBrokerExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int deleteShareBrokerByExample(ShareBrokerExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int deleteShareBrokerByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    void insertShareBroker(ShareBroker record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    void insertShareBrokerSelective(ShareBroker record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    List<ShareBroker> selectShareBrokerByExample(ShareBrokerExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    ShareBroker selectShareBrokerByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int updateShareBrokerByExampleSelective(ShareBroker record, ShareBrokerExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int updateShareBrokerByExample(ShareBroker record, ShareBrokerExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int updateShareBrokerByPrimaryKeySelective(ShareBroker record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table share_broker
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    int updateShareBrokerByPrimaryKey(ShareBroker record);
}