package com.prem.share.dm.db.dao;

import java.util.List;

import com.prem.share.dm.db.ShareBroker;
import com.prem.share.dm.db.ShareBrokerExample;

public interface ShareBrokerDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Tue Jun 28 11:24:18 IST 2011
	 */
	int countShareBrokerByExample(ShareBrokerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Tue Jun 28 11:24:18 IST 2011
	 */
	int deleteShareBrokerByExample(ShareBrokerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Tue Jun 28 11:24:18 IST 2011
	 */
	int deleteShareBrokerByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Tue Jun 28 11:24:18 IST 2011
	 */
	void insertShareBroker(ShareBroker record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Tue Jun 28 11:24:18 IST 2011
	 */
	void insertShareBrokerSelective(ShareBroker record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Tue Jun 28 11:24:18 IST 2011
	 */
	List<ShareBroker> selectShareBrokerByExample(ShareBrokerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Tue Jun 28 11:24:18 IST 2011
	 */
	ShareBroker selectShareBrokerByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Tue Jun 28 11:24:18 IST 2011
	 */
	int updateShareBrokerByExampleSelective(ShareBroker record,
			ShareBrokerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Tue Jun 28 11:24:18 IST 2011
	 */
	int updateShareBrokerByExample(ShareBroker record,
			ShareBrokerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Tue Jun 28 11:24:18 IST 2011
	 */
	int updateShareBrokerByPrimaryKeySelective(ShareBroker record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Tue Jun 28 11:24:18 IST 2011
	 */
	int updateShareBrokerByPrimaryKey(ShareBroker record);
}