package com.prem.share.dm.db.dao;

import com.prem.share.dm.db.ShareBroker;
import com.prem.share.dm.db.ShareBrokerExample;
import java.util.List;

public interface ShareBrokerDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	int countShareBrokerByExample(ShareBrokerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	int deleteShareBrokerByExample(ShareBrokerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	int deleteShareBrokerByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	void insertShareBroker(ShareBroker record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	void insertShareBrokerSelective(ShareBroker record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	List<ShareBroker> selectShareBrokerByExample(ShareBrokerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	ShareBroker selectShareBrokerByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	int updateShareBrokerByExampleSelective(ShareBroker record,
			ShareBrokerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	int updateShareBrokerByExample(ShareBroker record,
			ShareBrokerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	int updateShareBrokerByPrimaryKeySelective(ShareBroker record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table share_broker
	 * @ibatorgenerated  Wed Aug 04 18:25:48 GMT+05:30 2010
	 */
	int updateShareBrokerByPrimaryKey(ShareBroker record);
}