package com.prem.share.dm.db.dao.impl;

import com.prem.share.dm.db.CommodityTransaction;
import com.prem.share.dm.db.CommodityTransactionExample;
import com.prem.share.dm.db.dao.CommodityTransactionDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CommodityTransactionDAOImpl extends SqlMapClientDaoSupport implements CommodityTransactionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    public CommodityTransactionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    public int countCommodityTransactionByExample(CommodityTransactionExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("commodity_transaction.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    public int deleteCommodityTransactionByExample(CommodityTransactionExample example) {
        int rows = getSqlMapClientTemplate().delete("commodity_transaction.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    public int deleteCommodityTransactionByPrimaryKey(Integer transactionId) {
        CommodityTransaction key = new CommodityTransaction();
        key.setTransactionId(transactionId);
        int rows = getSqlMapClientTemplate().delete("commodity_transaction.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    public void insertCommodityTransaction(CommodityTransaction record) {
        getSqlMapClientTemplate().insert("commodity_transaction.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    public void insertCommodityTransactionSelective(CommodityTransaction record) {
        getSqlMapClientTemplate().insert("commodity_transaction.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    @SuppressWarnings("unchecked")
    public List<CommodityTransaction> selectCommodityTransactionByExample(CommodityTransactionExample example) {
        List<CommodityTransaction> list = getSqlMapClientTemplate().queryForList("commodity_transaction.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    public CommodityTransaction selectCommodityTransactionByPrimaryKey(Integer transactionId) {
        CommodityTransaction key = new CommodityTransaction();
        key.setTransactionId(transactionId);
        CommodityTransaction record = (CommodityTransaction) getSqlMapClientTemplate().queryForObject("commodity_transaction.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    public int updateCommodityTransactionByExampleSelective(CommodityTransaction record, CommodityTransactionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("commodity_transaction.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    public int updateCommodityTransactionByExample(CommodityTransaction record, CommodityTransactionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("commodity_transaction.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    public int updateCommodityTransactionByPrimaryKeySelective(CommodityTransaction record) {
        int rows = getSqlMapClientTemplate().update("commodity_transaction.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    public int updateCommodityTransactionByPrimaryKey(CommodityTransaction record) {
        int rows = getSqlMapClientTemplate().update("commodity_transaction.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table commodity_transaction
     *
     * @ibatorgenerated Mon Oct 24 16:28:18 IST 2011
     */
    private static class UpdateByExampleParms extends CommodityTransactionExample {
        private Object record;

        public UpdateByExampleParms(Object record, CommodityTransactionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}