package com.prem.share.dm.db.dao.impl;

import com.prem.share.dm.db.EquityTransaction;
import com.prem.share.dm.db.EquityTransactionExample;
import com.prem.share.dm.db.dao.EquityTransactionDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EquityTransactionDAOImpl extends SqlMapClientDaoSupport implements EquityTransactionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table equity_transaction
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	public EquityTransactionDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table equity_transaction
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	public int countEquityTransactionByExample(EquityTransactionExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"equity_transaction.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table equity_transaction
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	public int deleteEquityTransactionByExample(EquityTransactionExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"equity_transaction.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table equity_transaction
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	public int deleteEquityTransactionByPrimaryKey(Integer transactionId) {
		EquityTransaction key = new EquityTransaction();
		key.setTransactionId(transactionId);
		int rows = getSqlMapClientTemplate().delete(
				"equity_transaction.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table equity_transaction
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	public void insertEquityTransaction(EquityTransaction record) {
		getSqlMapClientTemplate().insert(
				"equity_transaction.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table equity_transaction
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	public void insertEquityTransactionSelective(EquityTransaction record) {
		getSqlMapClientTemplate().insert(
				"equity_transaction.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table equity_transaction
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	@SuppressWarnings("unchecked")
	public List<EquityTransaction> selectEquityTransactionByExample(
			EquityTransactionExample example) {
		List<EquityTransaction> list = getSqlMapClientTemplate().queryForList(
				"equity_transaction.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table equity_transaction
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	public EquityTransaction selectEquityTransactionByPrimaryKey(
			Integer transactionId) {
		EquityTransaction key = new EquityTransaction();
		key.setTransactionId(transactionId);
		EquityTransaction record = (EquityTransaction) getSqlMapClientTemplate()
				.queryForObject(
						"equity_transaction.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table equity_transaction
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	public int updateEquityTransactionByExampleSelective(
			EquityTransaction record, EquityTransactionExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"equity_transaction.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table equity_transaction
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	public int updateEquityTransactionByExample(EquityTransaction record,
			EquityTransactionExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"equity_transaction.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table equity_transaction
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	public int updateEquityTransactionByPrimaryKeySelective(
			EquityTransaction record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"equity_transaction.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table equity_transaction
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	public int updateEquityTransactionByPrimaryKey(EquityTransaction record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"equity_transaction.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table equity_transaction
	 * @ibatorgenerated  Tue Nov 16 20:05:25 GMT+05:30 2010
	 */
	private static class UpdateByExampleParms extends EquityTransactionExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				EquityTransactionExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}