package com.prem.share.dm.db.dao;

import com.prem.share.dm.db.brokerage;
import com.prem.share.dm.db.brokerageExample;
import java.util.List;

public interface brokerageDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table brokerage
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    int countbrokerageByExample(brokerageExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table brokerage
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    int deletebrokerageByExample(brokerageExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table brokerage
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    void insertbrokerage(brokerage record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table brokerage
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    void insertbrokerageSelective(brokerage record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table brokerage
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    List<brokerage> selectbrokerageByExample(brokerageExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table brokerage
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    int updatebrokerageByExampleSelective(brokerage record, brokerageExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table brokerage
     *
     * @ibatorgenerated Wed Jul 21 16:18:59 GMT+05:30 2010
     */
    int updatebrokerageByExample(brokerage record, brokerageExample example);
}